import { zipSync, strToU8 } from 'fflate'
import type { StoredSession } from '@unwrap/protocol'
import { buildStaticMirrorFiles } from './static-mirror'
import { generateMockServer } from './mock-export'

// Composes the runnable local-clone bundle: every captured static asset
// under frontend/, the mock server next to it, a run.sh that starts both,
// and a README explaining how to use it. The caller decides which session
// supplies the static assets and (separately) which session supplies the
// API surface — for project bundles these come from different sources so
// the frontend is the latest UI while the mock covers every captured call.
export function buildCloneBundle(opts: {
  // Session used as the source of static assets (HTML/CSS/JS/SVG bodies).
  // For a project bundle this is the most recent session; for a single-
  // session bundle it's the session itself.
  staticSource: StoredSession
  // Session used as the source of API call samples for the mock server.
  // For a project bundle this is a synthetic session whose apiCalls union
  // every captured call across the project.
  mockSource: StoredSession
  // Display label used in the README ("Local clone of example.com" vs.
  // "Local clone of session abcd1234").
  label: string
  // Filename stem — `clone-example.com-abcd1234.zip` etc.
  filenameStem: string
}): { filename: string; bytes: Uint8Array } {
  const mirror = buildStaticMirrorFiles(opts.staticSource)
  const mock = generateMockServer(opts.mockSource)

  const files: Record<string, Uint8Array> = {}
  // Mirror files go under frontend/ so run.sh can `cd frontend && python -m http.server`.
  for (const [path, bytes] of Object.entries(mirror.files)) {
    files[`frontend/${path}`] = bytes
  }
  files[mock.filename] = strToU8(mock.body)
  files['run.sh'] = strToU8(buildRunScript(mock.filename, mirror.hasSitemap))
  files['README.md'] = strToU8(buildReadme(opts, mock.filename, mirror))

  const bytes = zipSync(files, { level: 6 })
  return { filename: `${opts.filenameStem}.zip`, bytes }
}

function buildRunScript(mockFilename: string, hasSitemap: boolean): string {
  const sitemapHint = hasSitemap ? '/sitemap.html' : '/'
  return `#!/bin/sh
# Auto-generated by Unwrap. Starts the mock API server on :3000 and a
# static file server for the captured frontend on :8080.
set -e
cd "$(dirname "$0")"

if ! command -v node >/dev/null 2>&1; then
  echo "node is required to run the mock server. Install Node.js 18+ and re-run." >&2
  exit 1
fi

# Pick a static file server. python3 first, then python, then npx serve.
if command -v python3 >/dev/null 2>&1; then
  STATIC_CMD="python3 -m http.server 8080"
elif command -v python >/dev/null 2>&1; then
  STATIC_CMD="python -m SimpleHTTPServer 8080"
elif command -v npx >/dev/null 2>&1; then
  STATIC_CMD="npx --yes serve -l 8080 ."
else
  echo "Need python3, python, or npx to serve the frontend. Install one." >&2
  exit 1
fi

echo "→ starting mock API on http://localhost:3000"
node ${mockFilename} &
MOCK_PID=$!
trap "kill $MOCK_PID 2>/dev/null || true" EXIT INT TERM

# Give the mock server a moment to bind before we open the browser.
sleep 0.5
echo "→ starting frontend on http://localhost:8080"
echo "  open http://localhost:8080${sitemapHint} to explore."
cd frontend
exec $STATIC_CMD
`
}

function buildReadme(
  opts: { label: string },
  mockFilename: string,
  mirror: { inlined: unknown[]; urlOnly: unknown[]; hasSitemap: boolean },
): string {
  const lines: string[] = []
  lines.push(`# ${opts.label}`)
  lines.push('')
  lines.push('A runnable local clone generated by Unwrap from captured browser sessions.')
  lines.push('')
  lines.push('## Quick start')
  lines.push('')
  lines.push('```sh')
  lines.push('./run.sh')
  lines.push('```')
  lines.push('')
  lines.push('Then open <http://localhost:8080' + (mirror.hasSitemap ? '/sitemap.html' : '/') + '>.')
  lines.push('')
  lines.push('## What\'s inside')
  lines.push('')
  lines.push(`- \`frontend/\` — every captured HTML/CSS/JS/SVG asset (${mirror.inlined.length} bundled, ${mirror.urlOnly.length} URL-only references). Same-origin URLs in the HTML have been rewritten to relative paths so this serves cleanly behind any static server.`)
  lines.push(`- \`${mockFilename}\` — zero-dependency Node.js mock for every API endpoint observed. Returns the most representative 2xx response captured for each route, ignores path params, CORS open.`)
  lines.push('- `run.sh` — starts the mock on port 3000 and the frontend on port 8080. Auto-detects python3 / python / npx serve.')
  lines.push(`- \`frontend/${mirror.hasSitemap ? 'sitemap.html' : 'MIRROR.md'}\` — ${mirror.hasSitemap ? 'a clickable index of every page the user visited, with the API calls each page fired' : 'manifest of every captured asset'}.`)
  lines.push('')
  lines.push('## Caveats')
  lines.push('')
  lines.push('- The frontend will still hit the original host for any URL we did not capture (cross-origin scripts, images, fonts). Network panel will show the leftover requests.')
  lines.push('- The mock has no state — the same endpoint returns the same canned response every time. Flows that require sequenced responses (login → fetch → mutate → refetch) won\'t reproduce; future versions may replay the captured sequence.')
  lines.push('- Auth headers from the original capture are not bundled. Endpoints behind auth return the canned 2xx without checking.')
  lines.push('')
  return lines.join('\n')
}
