import type { ApiCall, StoredSession } from '@unwrap/protocol'

// Bundles the session's captured API calls into a single self-contained
// Node.js mock server. The output uses only `node:http` so the user can
// run it with `node mock-server.mjs` — no install step, no Hono.
export function generateMockServer(session: StoredSession): { filename: string; body: string } {
  const calls = session.summary.apiCalls ?? []
  const groups = groupForMock(calls)
  const routes = groups.map((g) => routeEntry(g))
  const filename = `mock-${safeHost(session.summary.meta.host)}-${session.id.slice(0, 8)}.mjs`

  const body = `#!/usr/bin/env node
// Generated by Unwrap from session ${session.id}
// Captured at ${session.summary.meta.startedAt}
// Source host: ${session.summary.meta.host || 'unknown'}
// Endpoints: ${groups.length}
//
// Run:
//   node ${filename}              # listens on :3000
//   PORT=8080 node ${filename}    # custom port
//
// Each route returns a captured response body verbatim. Path params are
// matched but ignored; the same canned body comes back regardless of id.
// Update / extend the ROUTES array below to tweak responses.

import { createServer } from 'node:http'
import { URL } from 'node:url'

const PORT = Number(process.env.PORT ?? 3000)

const ROUTES = ${JSON.stringify(routes, null, 2)}
  .map((r) => ({ ...r, pattern: new RegExp(r.pattern) }))

const CORS = {
  'access-control-allow-origin': '*',
  'access-control-allow-methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS',
  'access-control-allow-headers': '*',
  'access-control-max-age': '86400',
}

const server = createServer((req, res) => {
  if (req.method === 'OPTIONS') {
    res.writeHead(204, CORS)
    res.end()
    return
  }
  const url = new URL(req.url ?? '/', \`http://\${req.headers.host ?? 'localhost'}\`)
  const route = ROUTES.find(
    (r) => r.method === (req.method ?? '').toUpperCase() && r.pattern.test(url.pathname),
  )
  if (!route) {
    const lines = ROUTES.map((r) => \`  \${r.method.padEnd(6)} \${r.path}\`).join('\\n')
    res.writeHead(404, { 'content-type': 'text/plain', ...CORS })
    res.end(\`Mock has no route for \${req.method} \${url.pathname}\\n\\nAvailable routes:\\n\${lines}\\n\`)
    return
  }
  // Drain request body so client doesn't hang on POST/PUT.
  req.resume()
  const status = route.status || 200
  res.writeHead(status, {
    'content-type': route.mime || 'application/octet-stream',
    'x-mock-source': 'unwrap',
    ...CORS,
  })
  res.end(route.body ?? '')
  console.log(\`\${new Date().toISOString()} \${req.method} \${url.pathname} → \${status}\`)
})

server.listen(PORT, () => {
  console.log(\`unwrap mock server listening on http://localhost:\${PORT}\`)
  console.log(\`\${ROUTES.length} route\${ROUTES.length === 1 ? '' : 's'} loaded.\`)
})
`

  return { filename, body }
}

interface MockGroup {
  method: string
  hostname: string
  pathTemplate: string  // /users/{id}
  pathPattern: string   // ^/users/[^/]+$ (regex source)
  pickedCall: ApiCall
}

function groupForMock(calls: ApiCall[]): MockGroup[] {
  // Same signature key as the inventory page: group by method + normalized path
  const map = new Map<string, ApiCall[]>()
  for (const c of calls) {
    if (!c.method || !c.url) continue
    let hostname = ''
    let normalizedPath = c.url
    try {
      const u = new URL(c.url)
      hostname = u.host
      normalizedPath = normalizePath(u.pathname)
    } catch {
      // ignore
    }
    const gqlKey = c.graphql?.operationName ?? c.graphql?.queryHash ?? ''
    const key = `${c.method.toUpperCase()} ${hostname}${normalizedPath}${gqlKey ? `#${gqlKey}` : ''}`
    const list = map.get(key) ?? []
    list.push(c)
    map.set(key, list)
  }

  const out: MockGroup[] = []
  for (const list of map.values()) {
    // Prefer a 2xx sample with a non-empty body, fall back to whatever we have.
    const sorted = list
      .slice()
      .sort((a, b) => {
        const aPref = a.responseBody && a.status >= 200 && a.status < 300 ? 0 : 1
        const bPref = b.responseBody && b.status >= 200 && b.status < 300 ? 0 : 1
        if (aPref !== bPref) return aPref - bPref
        return 0
      })
    const picked = sorted[0]!
    let hostname = ''
    let normalizedPath = picked.url
    try {
      const u = new URL(picked.url)
      hostname = u.host
      normalizedPath = normalizePath(u.pathname)
    } catch {
      // ignore
    }
    out.push({
      method: picked.method.toUpperCase(),
      hostname,
      pathTemplate: normalizedPath,
      pathPattern: pathTemplateToRegex(normalizedPath),
      pickedCall: picked,
    })
  }
  // Sort: longest path first so /users/{id}/posts matches before /users/{id}
  out.sort((a, b) => b.pathTemplate.split('/').length - a.pathTemplate.split('/').length)
  return out
}

function routeEntry(g: MockGroup) {
  return {
    method: g.method,
    path: g.pathTemplate,
    pattern: g.pathPattern,
    status: g.pickedCall.status || 200,
    mime: g.pickedCall.responseMimeType || 'application/json',
    body: g.pickedCall.responseBody ?? '',
  }
}

function normalizePath(p: string): string {
  return (
    '/' +
    p
      .split('/')
      .filter(Boolean)
      .map((seg) => {
        if (/^\d+$/.test(seg)) return '{id}'
        if (/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(seg)) return '{uuid}'
        if (/^[0-9a-f]{24,}$/i.test(seg)) return '{hash}'
        return seg
      })
      .join('/')
  )
}

function pathTemplateToRegex(template: string): string {
  // /users/{id}/posts → ^/users/[^/]+/posts$
  // Escape regex metachars in literal segments; templates → [^/]+.
  const escaped = template
    .split('/')
    .map((seg) => {
      if (/^{.+}$/.test(seg)) return '[^/]+'
      return seg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    })
    .join('/')
  return `^${escaped}$`
}

function safeHost(host: string): string {
  return (host || 'session').replace(/[^a-zA-Z0-9.-]/g, '-').slice(0, 60)
}
