import { zipSync, strToU8 } from 'fflate'
import type { StaticAsset, StoredSession } from '@unwrap/protocol'

// Packs every captured text asset into a zip preserving the URL's
// pathname under <host>/. Binary assets (image/font) the extension
// only sent URL-only become entries in MIRROR.md instead of files —
// they're not on disk so we point at the source URL.
export function buildStaticMirrorZip(session: StoredSession): { filename: string; bytes: Uint8Array } {
  const assets = session.summary.staticAssets ?? []

  const files: Record<string, Uint8Array> = {}
  const usedPaths = new Set<string>()
  const inlined: { url: string; path: string; mime: string; size: number }[] = []
  const urlOnly: { url: string; mime: string; size: number; status: number }[] = []

  for (const a of assets) {
    if (a.urlOnly || a.body === undefined) {
      urlOnly.push({ url: a.url, mime: a.mimeType, size: a.size, status: a.status })
      continue
    }
    const path = filePathFor(a, usedPaths)
    files[path] = strToU8(a.body)
    inlined.push({ url: a.url, path, mime: a.mimeType, size: a.size })
  }

  files['MIRROR.md'] = strToU8(renderReadme(session, inlined, urlOnly))

  const bytes = zipSync(files, { level: 6 })
  const filename = `mirror-${safeHost(session.summary.meta.host)}-${session.id.slice(0, 8)}.zip`
  return { filename, bytes }
}

function filePathFor(a: StaticAsset, used: Set<string>): string {
  let host = ''
  let pathname = '/'
  let search = ''
  try {
    const u = new URL(a.url)
    host = u.host
    pathname = u.pathname || '/'
    search = u.search ? '__' + safeChunk(u.search) : ''
  } catch {
    host = 'unknown'
  }

  let segments = pathname.split('/').filter(Boolean).map(safeChunk)
  // For root URL or paths ending with slash, give index.html
  if (segments.length === 0 || pathname.endsWith('/')) {
    segments = [...segments, 'index.html']
  }

  // Ensure final segment has an extension. If not and the mime is HTML,
  // append .html so editors render it; for other mimes leave as-is.
  const last = segments[segments.length - 1]!
  if (!/\.[A-Za-z0-9]{1,8}$/.test(last)) {
    const ext = mimeToExt(a.mimeType)
    if (ext) segments[segments.length - 1] = `${last}.${ext}`
  }

  if (search) {
    const last = segments[segments.length - 1]!
    const dot = last.lastIndexOf('.')
    segments[segments.length - 1] = dot > 0 ? last.slice(0, dot) + search + last.slice(dot) : last + search
  }

  let path = `${safeChunk(host)}/${segments.join('/')}`
  // Dedupe — same URL hit twice already collapsed in extension, but
  // different search strings or normalized segments could still clash.
  let counter = 1
  let attempt = path
  while (used.has(attempt)) {
    const dot = path.lastIndexOf('.')
    attempt = dot > 0 ? `${path.slice(0, dot)}.${counter}${path.slice(dot)}` : `${path}.${counter}`
    counter++
  }
  used.add(attempt)
  return attempt
}

function safeChunk(s: string): string {
  return s.replace(/[^A-Za-z0-9._-]/g, '_').slice(0, 80) || '_'
}

function mimeToExt(mime: string): string | null {
  if (!mime) return null
  if (mime.startsWith('text/html')) return 'html'
  if (mime.startsWith('text/css')) return 'css'
  if (mime.includes('javascript')) return 'js'
  if (mime.includes('json')) return 'json'
  if (mime.includes('xml')) return 'xml'
  if (mime.includes('svg')) return 'svg'
  return null
}

function safeHost(host: string): string {
  return (host || 'session').replace(/[^a-zA-Z0-9.-]/g, '-').slice(0, 60)
}

function renderReadme(
  session: StoredSession,
  inlined: { url: string; path: string; mime: string; size: number }[],
  urlOnly: { url: string; mime: string; size: number; status: number }[],
): string {
  const meta = session.summary.meta
  const lines: string[] = []
  lines.push(`# Static mirror — ${meta.host || 'unknown host'}`)
  lines.push('')
  lines.push(`Generated by Unwrap from session \`${session.id}\``)
  lines.push(`Captured at ${meta.startedAt} · viewport ${meta.viewport.width}×${meta.viewport.height}`)
  lines.push('')
  lines.push("## What's here")
  lines.push('')
  lines.push(`- **${inlined.length}** text asset${inlined.length === 1 ? '' : 's'} (HTML / CSS / JS / SVG) inlined as files.`)
  lines.push(`- **${urlOnly.length}** binary reference${urlOnly.length === 1 ? '' : 's'} (image / font) listed below but not bundled — see the URLs to refetch from origin.`)
  lines.push('')
  lines.push('## How to use')
  lines.push('')
  lines.push('```sh')
  lines.push('unzip mirror-*.zip -d mirror && cd mirror')
  lines.push(`python -m http.server 8080            # serve over http://localhost:8080`)
  lines.push('```')
  lines.push('')
  lines.push('HTML files reference assets by absolute URL, so they will still load JS/CSS')
  lines.push('from the original host unless you rewrite the URLs or run a proxy.')
  lines.push('To pair with the captured backend, also download the mock server from the')
  lines.push('API inventory page and point your frontend at it.')
  lines.push('')
  lines.push('## Text assets bundled')
  lines.push('')
  if (inlined.length === 0) {
    lines.push('_(none)_')
  } else {
    lines.push('| Path | Source URL | Mime | Captured size |')
    lines.push('|---|---|---|---|')
    for (const a of inlined) {
      lines.push(`| \`${escapeMd(a.path)}\` | \`${escapeMd(a.url)}\` | ${escapeMd(a.mime)} | ${formatBytes(a.size)} |`)
    }
  }
  lines.push('')
  lines.push('## Binary references (URL only)')
  lines.push('')
  if (urlOnly.length === 0) {
    lines.push('_(none)_')
  } else {
    lines.push('| Source URL | Mime | Captured size | Status |')
    lines.push('|---|---|---|---|')
    for (const a of urlOnly) {
      lines.push(`| \`${escapeMd(a.url)}\` | ${escapeMd(a.mime)} | ${formatBytes(a.size)} | ${a.status} |`)
    }
  }
  lines.push('')
  return lines.join('\n')
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/`/g, '\\`')
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`
  return `${(n / (1024 * 1024)).toFixed(2)} MB`
}
