import { zipSync, strToU8 } from 'fflate'
import type { StoredSession } from '@unwrap/protocol'
import type { CanonicalTestRecord } from './storage/canonical-tests'
import { slugify } from './storage/canonical-tests'

export interface TestSuiteBundle {
  filename: string
  bytes: Uint8Array
  testCount: number
}

// Packs every canonical test for a project into a runnable Playwright
// project: one spec per canonical entry, a minimal playwright.config.ts
// at the root, a README explaining how to run, and a package.json with
// the @playwright/test dependency pinned.
//
// The result is a self-contained drop-in: unzip → `npm install` →
// `npx playwright test`. Fits straight into a CI step.
export function buildTestSuiteBundle(opts: {
  host: string
  canonical: CanonicalTestRecord[]
  // Sessions keyed by id so we can pull spec text per canonical entry.
  sessionsById: Map<string, StoredSession>
}): TestSuiteBundle {
  const files: Record<string, Uint8Array> = {}
  // Per-canonical name collisions are avoided by appending the short id.
  const used = new Set<string>()
  let included = 0
  const indexEntries: { fileName: string; name: string; tags: string[]; sessionId: string }[] = []

  for (const rec of opts.canonical) {
    const session = opts.sessionsById.get(rec.sessionId)
    if (!session?.generated?.spec) continue
    let base = slugify(rec.name || `test-${rec.sessionId.slice(0, 8)}`)
    let candidate = `${base}.spec.ts`
    let i = 1
    while (used.has(candidate)) {
      candidate = `${base}-${i}.spec.ts`
      i++
    }
    used.add(candidate)
    const header = renderSpecHeader(rec, session)
    const body = `${header}\n${session.generated.spec}\n`
    files[`tests/${candidate}`] = strToU8(body)
    indexEntries.push({ fileName: `tests/${candidate}`, name: rec.name, tags: rec.tags, sessionId: rec.sessionId })
    included++
  }

  files['playwright.config.ts'] = strToU8(renderPlaywrightConfig(opts.host))
  files['package.json'] = strToU8(renderPackageJson(opts.host))
  files['.gitignore'] = strToU8('node_modules\nplaywright-report\ntest-results\n')
  files['README.md'] = strToU8(renderReadme(opts.host, indexEntries))

  const safeHost = opts.host.replace(/[^a-zA-Z0-9.-]/g, '-').slice(0, 60) || 'project'
  return {
    filename: `tests-${safeHost}.zip`,
    bytes: zipSync(files, { level: 6 }),
    testCount: included,
  }
}

function renderSpecHeader(rec: CanonicalTestRecord, session: StoredSession): string {
  const meta = session.summary.meta
  const lines: string[] = []
  lines.push(`// ${rec.name}`)
  if (rec.tags.length > 0) lines.push(`// tags: ${rec.tags.join(', ')}`)
  lines.push(`// captured ${meta.startedAt} · session ${session.id}`)
  lines.push(`// duration ${meta.durationMs}ms · viewport ${meta.viewport.width}×${meta.viewport.height}`)
  lines.push('//')
  lines.push('// Generated by Unwrap. Re-generating the spec on the server will not')
  lines.push('// overwrite this file — re-export the bundle to pick up changes.')
  return lines.join('\n')
}

function renderPlaywrightConfig(host: string): string {
  return `import { defineConfig } from '@playwright/test'

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  reporter: 'list',
  use: {
    baseURL: process.env.BASE_URL ?? 'https://${host}',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  // No project-level browser pinning — pick yours with --project=… or
  // wire up the standard projects array below.
})
`
}

function renderPackageJson(host: string): string {
  const safeHost = host.replace(/[^a-z0-9-]+/g, '-').slice(0, 40) || 'project'
  return JSON.stringify(
    {
      name: `unwrap-tests-${safeHost}`,
      version: '0.0.0',
      private: true,
      scripts: {
        test: 'playwright test',
        'test:headed': 'playwright test --headed',
        report: 'playwright show-report',
      },
      devDependencies: {
        '@playwright/test': '^1.49.0',
      },
    },
    null,
    2,
  ) + '\n'
}

function renderReadme(host: string, entries: { fileName: string; name: string; tags: string[]; sessionId: string }[]): string {
  const lines: string[] = []
  lines.push(`# ${host} test suite`)
  lines.push('')
  lines.push('Curated by Unwrap from sessions you marked canonical. Each spec is')
  lines.push('a snapshot of a captured flow + Gemini-generated assertions.')
  lines.push('')
  lines.push('## Run')
  lines.push('```sh')
  lines.push('npm install')
  lines.push('npx playwright install chromium')
  lines.push('npx playwright test')
  lines.push('```')
  lines.push('')
  lines.push('Point at a different environment with `BASE_URL=https://staging.example.com npx playwright test`.')
  lines.push('')
  lines.push(`## Specs (${entries.length})`)
  lines.push('')
  if (entries.length === 0) {
    lines.push('_(none — mark some session specs as canonical from their session detail pages)_')
  } else {
    lines.push('| File | Name | Tags | Source session |')
    lines.push('|---|---|---|---|')
    for (const e of entries) {
      lines.push(`| \`${e.fileName}\` | ${e.name} | ${e.tags.join(', ') || '—'} | \`${e.sessionId}\` |`)
    }
  }
  lines.push('')
  lines.push('## Update workflow')
  lines.push('')
  lines.push('1. Regenerate any spec from the session detail page in Unwrap when its UI changes.')
  lines.push('2. Re-download this bundle from `/projects/<host>/tests` — every canonical spec is re-pulled.')
  lines.push('3. Commit the new bundle in your repo or have CI fetch on each run.')
  lines.push('')
  return lines.join('\n')
}
