import type { ErrorResponse, GenerateRequest, GenerateResponse } from '@unwrap/protocol'
import { getSession, listEvents } from '@/shared/storage'
import type { SessionMeta } from '@/shared/events'
import { authedFetch } from './auth'
import type { ExportResult } from './export'
import { generatePlaywrightScript } from './playwright'
import { pickScreenshotsForLlm } from './screenshots'
import { summarizeSession } from './summarize'

export async function generateAiTest(sessionId: string): Promise<ExportResult> {
  const meta = await getSession(sessionId)
  if (!meta) throw new Error('session not found')
  const events = await listEvents(sessionId)

  const summary = summarizeSession(meta, events)
  const fallbackSpec = generatePlaywrightScript(meta, events)
  const screenshots = await pickScreenshotsForLlm(sessionId, events, 2)

  const body: GenerateRequest = {
    sessionId,
    summary,
    fallbackSpec,
    screenshots,
  }

  const resp = await authedFetch('/api/generate', {
    method: 'POST',
    body: JSON.stringify(body),
  })

  if (!resp.ok) {
    let message = `Server returned ${resp.status}`
    try {
      const j = (await resp.json()) as ErrorResponse
      if (j.error) message = j.detail ? `${j.error}: ${j.detail}` : j.error
    } catch {
      // fall through to status-only message
    }
    throw new Error(message)
  }

  const result = (await resp.json()) as GenerateResponse
  console.info(
    `[unwrap] gemini ${result.model} prompt=${result.usage.promptTokens} out=${result.usage.candidatesTokens} total=${result.usage.totalTokens}`,
  )

  const header = buildHeaderComment(meta, result)
  const content = header + '\n\n' + result.spec.trim() + '\n'
  const blob = new Blob([content], { type: 'text/typescript' })
  return download(blob, `${safeName(meta)}.ai.spec.ts`)
}

function buildHeaderComment(meta: SessionMeta, result: GenerateResponse): string {
  const lines: string[] = [
    '// Generated by Unwrap (AI-assisted via Gemini through @unwrap/server)',
    `// model: ${result.model}`,
    `// session: ${meta.id}`,
    `// assertions added beyond replay: ${result.assertionsAdded}`,
    '//',
  ]
  for (const l of result.description.split('\n')) lines.push(`// ${l}`)
  if (result.warnings.length) {
    lines.push('//')
    lines.push('// WARNINGS:')
    for (const w of result.warnings) lines.push(`// - ${w}`)
  }
  return lines.join('\n')
}

function safeName(meta: SessionMeta): string {
  const dt = new Date(meta.startedAt).toISOString().replace(/[:.]/g, '-')
  let host = 'session'
  try {
    host = new URL(meta.startUrl).host || 'session'
  } catch {
    // ignore
  }
  return `unwrap-${host}-${dt}`
}

async function download(blob: Blob, filename: string): Promise<ExportResult> {
  const dataUrl = await blobToDataUrl(blob)
  const downloadId = await chrome.downloads.download({ url: dataUrl, filename, saveAs: true })
  return { filename, downloadId }
}

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result))
    reader.onerror = () => reject(reader.error)
    reader.readAsDataURL(blob)
  })
}
