import { Layout } from './_layout'
import { Button } from '../components/ui/button'
import type { ProjectNarrative } from '../project-narrative'

export function ProjectNarrativePage({ email, host, narrative, error }: {
  email: string
  host: string
  narrative?: ProjectNarrative
  error?: string
}) {
  return (
    <Layout email={email}>
      <p className="m-0 mb-3"><a href={`/projects/${encodeURIComponent(host)}`} className="text-primary text-sm">← back to {host}</a></p>

      {error && <div className="rounded-md border border-[hsl(var(--danger))]/40 bg-[hsl(var(--danger))]/5 p-3 text-sm text-[hsl(var(--danger))] mb-3">{error}</div>}

      {narrative
        ? (
          <>
            <div className="flex justify-between items-baseline flex-wrap gap-2 mb-3">
              <div className="text-xs text-muted-foreground">
                Generated by {narrative.model} · {new Date(narrative.generatedAt).toISOString().replace('T', ' ').slice(0, 16)} · {narrative.usage.totalTokens} tokens · across {narrative.sessionCount} session{narrative.sessionCount === 1 ? '' : 's'}
              </div>
              <form method="post" action={`/projects/${encodeURIComponent(host)}/narrative/regenerate`}>
                <Button type="submit" variant="secondary" size="sm">↻ Regenerate</Button>
              </form>
            </div>
            <article className="prose prose-sm dark:prose-invert max-w-none [&_h1]:text-2xl [&_h1]:font-bold [&_h1]:mb-1 [&_h2]:text-base [&_h2]:font-semibold [&_h2]:mt-6 [&_h2]:mb-2 [&_h2]:pt-3 [&_h2]:border-t [&_h3]:text-sm [&_h3]:font-semibold [&_h3]:mt-4 [&_h3]:mb-1 [&_p]:my-2 [&_ul]:my-2 [&_ul]:pl-5 [&_li]:my-1 [&_code]:rounded [&_code]:bg-muted [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:text-xs [&_em]:text-muted-foreground" dangerouslySetInnerHTML={{ __html: markdownToHtml(narrative.markdown) }} />
          </>
        )
        : (
          <div className="text-center py-12">
            <p className="text-muted-foreground">No narrative yet. Click below to generate one — this calls Gemini with the captured screenshots, API surface, and GraphQL ops.</p>
            <form method="post" action={`/projects/${encodeURIComponent(host)}/narrative/regenerate`} className="mt-4">
              <Button type="submit">Generate service brief</Button>
            </form>
          </div>
        )}
    </Layout>
  )
}

function markdownToHtml(md: string): string {
  const lines = md.split('\n')
  const out: string[] = []
  let inList: 'ul' | null = null
  let paragraph: string[] = []
  const flushParagraph = () => { if (paragraph.length === 0) return; out.push(`<p>${inlineMarkup(paragraph.join(' '))}</p>`); paragraph = [] }
  const closeList = () => { if (inList) { out.push(`</${inList}>`); inList = null } }
  for (const line of lines) {
    if (/^#{1,6}\s/.test(line)) {
      flushParagraph(); closeList()
      const level = line.match(/^#+/)![0].length
      out.push(`<h${level}>${inlineMarkup(line.slice(level + 1))}</h${level}>`)
      continue
    }
    if (/^- \[[ x]\]\s/.test(line)) {
      flushParagraph()
      if (inList !== 'ul') { closeList(); out.push('<ul class="list-none pl-0">'); inList = 'ul' }
      const checked = line[3] === 'x'
      out.push(`<li class="my-1"><input type="checkbox" disabled${checked ? ' checked' : ''} class="mr-1.5"> ${inlineMarkup(line.slice(6))}</li>`)
      continue
    }
    if (/^[-*]\s/.test(line)) {
      flushParagraph()
      if (inList !== 'ul') { closeList(); out.push('<ul>'); inList = 'ul' }
      out.push(`<li>${inlineMarkup(line.slice(2))}</li>`)
      continue
    }
    if (line.trim() === '') { flushParagraph(); closeList(); continue }
    paragraph.push(line)
  }
  flushParagraph(); closeList()
  return out.join('\n')
}

function inlineMarkup(s: string): string {
  let out = s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  out = out.replace(/`([^`]+)`/g, '<code>$1</code>')
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  out = out.replace(/\*([^*]+)\*/g, '<em>$1</em>')
  out = out.replace(/_([^_]+)_/g, '<em>$1</em>')
  return out
}
