import { html, raw } from 'hono/html'
import { Layout, type Renderable } from './layout'
import type { ProjectNarrative } from '../project-narrative'

export function ProjectNarrativePage({
  email,
  host,
  narrative,
  error,
}: {
  email: string
  host: string
  narrative?: ProjectNarrative
  error?: string
}): Renderable {
  return Layout({
    title: `${host} · service brief`,
    email,
    body: html`
      <p><a href="/projects/${encodeURIComponent(host)}">← back to ${host}</a></p>

      ${error
        ? html`<div class="error">${error}</div>`
        : ''}

      ${narrative
        ? html`
          <div style="display: flex; justify-content: space-between; align-items: baseline; flex-wrap: wrap; gap: 8px; margin-bottom: 12px;">
            <div class="meta" style="font-size: 11px;">
              Generated by ${narrative.model} · ${new Date(narrative.generatedAt).toISOString().replace('T', ' ').slice(0, 16)} · ${narrative.usage.totalTokens} tokens · across ${narrative.sessionCount} session${narrative.sessionCount === 1 ? '' : 's'}
            </div>
            <form method="post" action="/projects/${encodeURIComponent(host)}/narrative/regenerate" style="margin: 0;">
              <button class="btn secondary" type="submit">↻ Regenerate</button>
            </form>
          </div>
          <article class="narrative">${raw(markdownToHtml(narrative.markdown))}</article>
        `
        : html`
          <div class="empty">
            <p>No narrative yet. Click below to generate one — this calls Gemini with the captured screenshots, API surface, and GraphQL ops.</p>
            <form method="post" action="/projects/${encodeURIComponent(host)}/narrative/regenerate" style="margin-top: 16px;">
              <button class="btn" type="submit">Generate service brief</button>
            </form>
          </div>
        `}

      <style>${raw(NARRATIVE_CSS)}</style>
    `,
  })
}

// Tiny markdown → HTML converter. Covers headings, bullets, checkbox lists,
// bold, italic, code, and paragraphs — the subset the narrative actually
// emits. Avoids pulling a markdown lib into the worker bundle.
function markdownToHtml(md: string): string {
  const lines = md.split('\n')
  const out: string[] = []
  let inList: 'ul' | 'ol' | null = null
  let paragraph: string[] = []

  const flushParagraph = () => {
    if (paragraph.length === 0) return
    out.push(`<p>${inlineMarkup(paragraph.join(' '))}</p>`)
    paragraph = []
  }
  const closeList = () => {
    if (inList) {
      out.push(`</${inList}>`)
      inList = null
    }
  }

  for (const line of lines) {
    if (/^#{1,6}\s/.test(line)) {
      flushParagraph()
      closeList()
      const level = line.match(/^#+/)![0].length
      const text = line.slice(level + 1)
      out.push(`<h${level}>${inlineMarkup(text)}</h${level}>`)
      continue
    }
    if (/^- \[[ x]\]\s/.test(line)) {
      flushParagraph()
      if (inList !== 'ul') {
        closeList()
        out.push('<ul class="checklist">')
        inList = 'ul'
      }
      const checked = line[3] === 'x'
      const text = line.slice(6)
      out.push(`<li><input type="checkbox" disabled ${checked ? 'checked' : ''}> ${inlineMarkup(text)}</li>`)
      continue
    }
    if (/^[-*]\s/.test(line)) {
      flushParagraph()
      if (inList !== 'ul') {
        closeList()
        out.push('<ul>')
        inList = 'ul'
      }
      out.push(`<li>${inlineMarkup(line.slice(2))}</li>`)
      continue
    }
    if (line.trim() === '') {
      flushParagraph()
      closeList()
      continue
    }
    paragraph.push(line)
  }
  flushParagraph()
  closeList()
  return out.join('\n')
}

function inlineMarkup(s: string): string {
  // Escape HTML first
  let out = s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
  // `code`
  out = out.replace(/`([^`]+)`/g, '<code>$1</code>')
  // **bold** before *italic* so the regex doesn't eat the bold markers.
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  out = out.replace(/\*([^*]+)\*/g, '<em>$1</em>')
  out = out.replace(/_([^_]+)_/g, '<em>$1</em>')
  return out
}

const NARRATIVE_CSS = `
.narrative { line-height: 1.65; }
.narrative h1 { font-size: 22px; margin: 0 0 4px; }
.narrative h2 { font-size: 16px; margin: 28px 0 8px; padding-top: 12px; border-top: 1px solid var(--border); text-transform: none; letter-spacing: 0; color: var(--fg); font-weight: 600; }
.narrative h3 { font-size: 14px; margin: 18px 0 6px; font-weight: 600; }
.narrative p { margin: 8px 0; }
.narrative ul { margin: 6px 0; padding-left: 22px; }
.narrative li { margin: 4px 0; }
.narrative ul.checklist { list-style: none; padding-left: 0; }
.narrative ul.checklist input { margin-right: 6px; }
.narrative code { background: rgba(127, 127, 127, 0.12); padding: 1px 5px; border-radius: 4px; font-size: 12px; }
.narrative em { color: var(--muted); }
`
