import { Layout } from './_layout'
import { Button } from '@unwrap/ui'
import type { ProjectTestPlan } from '../project-test-plan'

export function TestPlanPage({ email, host, plan, error }: { email: string; host: string; plan?: ProjectTestPlan; error?: string }) {
  return (
    <Layout email={email} wide>
      <p className="m-0 mb-2"><a href={`/projects/${encodeURIComponent(host)}`} className="text-primary text-sm">← back to {host}</a></p>
      <h2 className="m-0 text-xl font-bold">AI test plan</h2>
      <p className="text-xs text-muted-foreground mt-1 mb-4">
        Gemini reads the project's known surface, your existing coverage, and your canonical suite, then proposes a prioritized list of test scenarios to fill the gaps.
        Every scenario cites specific evidence from the captures and includes Playwright-flavored assertions ready to translate into spec code.
      </p>

      {error && <div className="rounded-md bg-danger/10 border border-danger/30 text-danger p-3 text-sm mb-3">{error}</div>}

      {plan
        ? (
          <>
            <div className="flex justify-between items-baseline flex-wrap gap-2 mb-3">
              <div className="text-xs text-muted-foreground">
                Generated by {plan.model} · {new Date(plan.generatedAt).toISOString().replace('T', ' ').slice(0, 16)} ·{' '}
                {plan.usage.totalTokens} tokens · across {plan.sessionCount} session{plan.sessionCount === 1 ? '' : 's'}
                {' · '}{plan.canonicalCount} canonical spec{plan.canonicalCount === 1 ? '' : 's'} considered ·{' '}
                <strong>{plan.scenarios.length} scenarios</strong>
              </div>
              <form method="post" action={`/projects/${encodeURIComponent(host)}/test-plan/regenerate`} className="m-0">
                <Button variant="secondary" size="sm" type="submit">↻ Regenerate</Button>
              </form>
            </div>
            <article className="prose-plan leading-relaxed" dangerouslySetInnerHTML={{ __html: markdownToHtml(plan.markdown) }} />
          </>
        )
        : (
          <div className="text-center text-muted-foreground py-12">
            <p>No test plan yet. Generating one calls Gemini with the project's surface + coverage data — costs a few cents.</p>
            <form method="post" action={`/projects/${encodeURIComponent(host)}/test-plan/regenerate`} className="mt-4">
              <Button type="submit">Generate test plan</Button>
            </form>
          </div>
        )}
    </Layout>
  )
}

function markdownToHtml(md: string): string {
  const lines = md.split('\n')
  const out: string[] = []
  let inList: 'ul' | null = null
  let paragraph: string[] = []
  const flush = () => {
    if (paragraph.length === 0) return
    out.push(`<p>${inlineMarkup(paragraph.join(' '))}</p>`)
    paragraph = []
  }
  const closeList = () => {
    if (inList) { out.push(`</${inList}>`); inList = null }
  }
  for (const line of lines) {
    if (/^#{1,6}\s/.test(line)) {
      flush(); closeList()
      const level = line.match(/^#+/)![0].length
      out.push(`<h${level} class="mt-7 mb-2 pt-3 border-t font-semibold text-base">${inlineMarkup(line.slice(level + 1))}</h${level}>`)
      continue
    }
    if (/^[-*]\s/.test(line)) {
      flush()
      if (inList !== 'ul') { closeList(); out.push('<ul class="list-disc pl-6 my-1">'); inList = 'ul' }
      out.push(`<li class="my-1">${inlineMarkup(line.slice(2))}</li>`)
      continue
    }
    if (line.trim() === '') { flush(); closeList(); continue }
    paragraph.push(line)
  }
  flush(); closeList()
  return out.join('\n')
}

function inlineMarkup(s: string): string {
  let out = s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  out = out.replace(/`([^`]+)`/g, '<code class="rounded bg-muted px-1.5 py-0.5 text-xs">$1</code>')
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  out = out.replace(/\*([^*]+)\*/g, '<em class="text-muted-foreground italic">$1</em>')
  return out
}
