import { html, raw } from 'hono/html'
import { Layout, type Renderable } from './layout'
import type { ProjectTestPlan } from '../project-test-plan'

export function TestPlanPage({
  email,
  host,
  plan,
  error,
}: {
  email: string
  host: string
  plan?: ProjectTestPlan
  error?: string
}): Renderable {
  return Layout({
    title: `${host} · test plan`,
    email,
    body: html`
      <p><a href="/projects/${encodeURIComponent(host)}">← back to ${host}</a></p>
      <h2 style="margin-top: 4px;">AI test plan</h2>
      <p class="muted">
        Gemini reads the project's known surface, your existing coverage, and your canonical
        suite, then proposes a prioritized list of test scenarios to fill the gaps. Every
        scenario cites specific evidence from the captures and includes Playwright-flavored
        assertions ready to translate into spec code.
      </p>

      ${error ? html`<div class="error">${error}</div>` : ''}

      ${plan
        ? html`
          <div style="display: flex; justify-content: space-between; align-items: baseline; flex-wrap: wrap; gap: 8px; margin-bottom: 12px;">
            <div class="meta" style="font-size: 11px;">
              Generated by ${plan.model} · ${new Date(plan.generatedAt).toISOString().replace('T', ' ').slice(0, 16)} ·
              ${plan.usage.totalTokens} tokens · across ${plan.sessionCount} session${plan.sessionCount === 1 ? '' : 's'}
              · ${plan.canonicalCount} canonical spec${plan.canonicalCount === 1 ? '' : 's'} considered ·
              <strong>${plan.scenarios.length} scenarios</strong>
            </div>
            <form method="post" action="/projects/${encodeURIComponent(host)}/test-plan/regenerate" style="margin: 0;">
              <button class="btn secondary" type="submit">↻ Regenerate</button>
            </form>
          </div>
          <article class="plan">${raw(markdownToHtml(plan.markdown))}</article>
        `
        : html`
          <div class="empty">
            <p>No test plan yet. Generating one calls Gemini with the project's surface + coverage data — costs a few cents.</p>
            <form method="post" action="/projects/${encodeURIComponent(host)}/test-plan/regenerate" style="margin-top: 16px;">
              <button class="btn" type="submit">Generate test plan</button>
            </form>
          </div>
        `}

      <style>${raw(PLAN_CSS)}</style>
    `,
  })
}

// Same tiny markdown→HTML converter as the narrative page (covers
// headings, bullets, bold, italic, code). Avoids pulling a markdown
// parser into the Worker bundle.
function markdownToHtml(md: string): string {
  const lines = md.split('\n')
  const out: string[] = []
  let inList: 'ul' | null = null
  let paragraph: string[] = []
  const flush = () => {
    if (paragraph.length === 0) return
    out.push(`<p>${inlineMarkup(paragraph.join(' '))}</p>`)
    paragraph = []
  }
  const closeList = () => {
    if (inList) { out.push(`</${inList}>`); inList = null }
  }
  for (const line of lines) {
    if (/^#{1,6}\s/.test(line)) {
      flush(); closeList()
      const level = line.match(/^#+/)![0].length
      out.push(`<h${level}>${inlineMarkup(line.slice(level + 1))}</h${level}>`)
      continue
    }
    if (/^[-*]\s/.test(line)) {
      flush()
      if (inList !== 'ul') { closeList(); out.push('<ul>'); inList = 'ul' }
      out.push(`<li>${inlineMarkup(line.slice(2))}</li>`)
      continue
    }
    if (line.trim() === '') { flush(); closeList(); continue }
    paragraph.push(line)
  }
  flush(); closeList()
  return out.join('\n')
}

function inlineMarkup(s: string): string {
  let out = s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  out = out.replace(/`([^`]+)`/g, '<code>$1</code>')
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  out = out.replace(/\*([^*]+)\*/g, '<em>$1</em>')
  return out
}

const PLAN_CSS = `
.plan { line-height: 1.65; }
.plan h2 { font-size: 17px; margin: 28px 0 8px; padding-top: 12px; border-top: 1px solid var(--border); }
.plan h3 { font-size: 14px; margin: 18px 0 4px; font-weight: 600; }
.plan p { margin: 6px 0; }
.plan ul { margin: 4px 0 6px; padding-left: 22px; }
.plan li { margin: 3px 0; }
.plan code { background: rgba(127,127,127,0.12); padding: 1px 5px; border-radius: 4px; font-size: 12px; word-break: break-all; }
.plan strong { font-weight: 600; }
.plan em { color: var(--muted); font-style: italic; }
`
